# Generated by Django 2.2.6 on 2019-11-03 12:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import project.bots.response.response_answer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=256)),
                ('confirm_code', models.CharField(default='', max_length=256)),
                ('group_id', models.BigIntegerField(unique=True)),
                ('secret_key', models.CharField(default='', max_length=256)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('names', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1024)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=project.bots.response.response_answer.ResponseAnswer.default_answer_structure)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.BotModel')),
            ],
        ),
    ]
