# Generated by Django 2.2.6 on 2019-10-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bots',
            new_name='BotModel',
        ),
    ]
