# Generated by Django 2.2.6 on 2019-10-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20191015_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='confirm_code',
            field=models.CharField(default='', max_length=256),
        ),
    ]
