# Generated by Django 2.2.6 on 2019-11-03 13:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import project.bots.models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20191103_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='names',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=project.bots.models.default_names),
        ),
    ]
