# Generated by Django 2.2.6 on 2019-10-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botmodel_confirm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='group_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
