# Generated by Django 2.2.6 on 2019-11-07 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botmodel_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.BigIntegerField(unique=True)),
                ('coins', models.BigIntegerField(default=0)),
                ('vip_expire', models.DateTimeField(default=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
