# Generated by Django 2.2.6 on 2019-11-07 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='vip_expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
