# Generated by Django 2.2.6 on 2019-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_auto_20191107_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
