# Generated by Django 2.2.6 on 2019-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_auto_20191015_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botmodel',
            name='secret_key',
            field=models.CharField(default='', max_length=256),
        ),
    ]
